// Auto-generated by scripts/generate-games-data.js — do not edit manually
// 170 games from thumbnails/

export const GAME_BASE_URL = 'https://html5games.plak365games.com';

export const CATEGORY_KEYS = {
  "top-10-games": "Top 10 Games",
  "vip-games": "VIP Games",
  "games-with-leaderboard": "Games with Leaderboard",
  "train-your-brain": "Train Your Brain",
  "soothing": "Soothing",
  "quick-break-at-work": "Quick Break at Work",
  "sports": "Sports",
  "multiplayer": "Multiplayer",
  "all-games": "All Games"
};

export const GAMES_DATA = [
  {
    "id": 1,
    "name": "5 Fruit",
    "slug": "5fruit",
    "url": "https://html5games.plak365games.com/5fruit/",
    "thumbnail": "./thumbnails/5fruit.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 2,
    "name": "Aircraft",
    "slug": "aircraft",
    "url": "https://html5games.plak365games.com/aircraft/",
    "thumbnail": "./thumbnails/aircraft.png",
    "categories": [
      "All Games",
      "Arcade"
    ]
  },
  {
    "id": 3,
    "name": "Airhockey",
    "slug": "airhockey",
    "url": "https://html5games.plak365games.com/airhockey/",
    "thumbnail": "./thumbnails/airhockey.png",
    "categories": [
      "All Games",
      "Sports",
      "Multiplayer",
      "Top 10 Games"
    ]
  },
  {
    "id": 4,
    "name": "Airportrush",
    "slug": "airportrush",
    "url": "https://html5games.plak365games.com/airportrush/",
    "thumbnail": "./thumbnails/airportrush.ico",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 5,
    "name": "Avenger",
    "slug": "avenger",
    "url": "https://html5games.plak365games.com/avenger/",
    "thumbnail": "./thumbnails/avenger.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Action"
    ]
  },
  {
    "id": 6,
    "name": "Avengerhydrarush",
    "slug": "avengerhydrarush",
    "url": "https://html5games.plak365games.com/avengerhydrarush/",
    "thumbnail": "./thumbnails/avengerhydrarush.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Quick Break at Work",
      "Easy to Play",
      "Action",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 7,
    "name": "Babel",
    "slug": "babel",
    "url": "https://html5games.plak365games.com/babel/",
    "thumbnail": "./thumbnails/babel.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 8,
    "name": "Babelic",
    "slug": "babelic",
    "url": "https://html5games.plak365games.com/babelic/",
    "thumbnail": "./thumbnails/babelic.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 9,
    "name": "Ball Jump",
    "slug": "ball-jump",
    "url": "https://html5games.plak365games.com/ball-jump/",
    "thumbnail": "./thumbnails/ball-jump.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 10,
    "name": "Ball Rush",
    "slug": "ball-rush",
    "url": "https://html5games.plak365games.com/ball-rush/",
    "thumbnail": "./thumbnails/ball-rush.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 11,
    "name": "Balloonparadise",
    "slug": "balloonparadise",
    "url": "https://html5games.plak365games.com/balloonparadise/",
    "thumbnail": "./thumbnails/balloonparadise.png",
    "categories": [
      "All Games",
      "Soothing",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 12,
    "name": "Ballup",
    "slug": "ballup",
    "url": "https://html5games.plak365games.com/ballup/",
    "thumbnail": "./thumbnails/ballup.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 13,
    "name": "Barbie Cooking",
    "slug": "barbie-cooking",
    "url": "https://html5games.plak365games.com/barbie-cooking/",
    "thumbnail": "./thumbnails/barbie-cooking.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 14,
    "name": "Barbie Sparkle",
    "slug": "barbie-sparkle",
    "url": "https://html5games.plak365games.com/barbie-sparkle/",
    "thumbnail": "./thumbnails/barbie-sparkle.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 15,
    "name": "Barbiemakeup",
    "slug": "barbiemakeup",
    "url": "https://html5games.plak365games.com/barbiemakeup/",
    "thumbnail": "./thumbnails/barbiemakeup.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 16,
    "name": "Bearchase",
    "slug": "bearchase",
    "url": "https://html5games.plak365games.com/bearchase/",
    "thumbnail": "./thumbnails/bearchase.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 17,
    "name": "Beerpushing",
    "slug": "beerpushing",
    "url": "https://html5games.plak365games.com/beerpushing/",
    "thumbnail": "./thumbnails/beerpushing.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 18,
    "name": "Bikespeed",
    "slug": "bikespeed",
    "url": "https://html5games.plak365games.com/bikespeed/",
    "thumbnail": "./thumbnails/bikespeed.png",
    "categories": [
      "All Games",
      "Arcade",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 19,
    "name": "Bingo",
    "slug": "bingo",
    "url": "https://html5games.plak365games.com/bingo/",
    "thumbnail": "./thumbnails/bingo.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle",
      "Top 10 Games"
    ]
  },
  {
    "id": 20,
    "name": "Birds Jump",
    "slug": "birds-jump",
    "url": "https://html5games.plak365games.com/birds-jump/",
    "thumbnail": "./thumbnails/birds-jump.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 21,
    "name": "Blockit",
    "slug": "blockit",
    "url": "https://html5games.plak365games.com/blockit/",
    "thumbnail": "./thumbnails/blockit.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 22,
    "name": "Bluestory",
    "slug": "bluestory",
    "url": "https://html5games.plak365games.com/bluestory/",
    "thumbnail": "./thumbnails/bluestory.png",
    "categories": [
      "All Games",
      "Soothing"
    ]
  },
  {
    "id": 23,
    "name": "Boom Car",
    "slug": "boom-car",
    "url": "https://html5games.plak365games.com/boom-car/",
    "thumbnail": "./thumbnails/boom-car.png",
    "categories": [
      "All Games",
      "Arcade"
    ]
  },
  {
    "id": 24,
    "name": "Bottle Shoot",
    "slug": "bottle-shoot",
    "url": "https://html5games.plak365games.com/bottle-shoot/",
    "thumbnail": "./thumbnails/bottle-shoot-copy.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 25,
    "name": "Bottle Shoot",
    "slug": "bottle-shoot",
    "url": "https://html5games.plak365games.com/bottle-shoot/",
    "thumbnail": "./thumbnails/bottle-shoot.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 26,
    "name": "Bubbles",
    "slug": "bubbles",
    "url": "https://html5games.plak365games.com/bubbles/",
    "thumbnail": "./thumbnails/bubbles.png",
    "categories": [
      "All Games",
      "Soothing"
    ]
  },
  {
    "id": 27,
    "name": "Bugs Bunny Carrot Chase",
    "slug": "bugs-bunny-carrot-chase",
    "url": "https://html5games.plak365games.com/bugs-bunny-carrot-chase/",
    "thumbnail": "./thumbnails/bugs-bunny-carrot-chase.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Arcade"
    ]
  },
  {
    "id": 28,
    "name": "Bugs Bunny Dare Diver",
    "slug": "bugs-bunny-dare-diver",
    "url": "https://html5games.plak365games.com/bugs-bunny-dare-diver/",
    "thumbnail": "./thumbnails/bugs-bunny-dare-diver.ico",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 29,
    "name": "Bunnicula And The Cursed Diamond",
    "slug": "bunnicula-and-the-cursed-diamond",
    "url": "https://html5games.plak365games.com/bunnicula-and-the-cursed-diamond/",
    "thumbnail": "./thumbnails/bunnicula-and-the-cursed-diamond.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 30,
    "name": "Bunnicula Crop Control",
    "slug": "bunnicula-crop-control",
    "url": "https://html5games.plak365games.com/bunnicula-crop-control/",
    "thumbnail": "./thumbnails/bunnicula-crop-control.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 31,
    "name": "Bunnicula Juicy Bites",
    "slug": "bunnicula-juicy-bites",
    "url": "https://html5games.plak365games.com/bunnicula-juicy-bites/",
    "thumbnail": "./thumbnails/bunnicula-juicy-bites.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 32,
    "name": "Bunnicula Kaotic Kitchen",
    "slug": "bunnicula-kaotic-kitchen",
    "url": "https://html5games.plak365games.com/bunnicula-kaotic-kitchen/",
    "thumbnail": "./thumbnails/bunnicula-kaotic-kitchen.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 33,
    "name": "Bunnicula Monster Match",
    "slug": "bunnicula-monster-match",
    "url": "https://html5games.plak365games.com/bunnicula-monster-match/",
    "thumbnail": "./thumbnails/bunnicula-monster-match.ico",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 34,
    "name": "Bunnicula Rescuing Harold",
    "slug": "bunnicula-rescuing-harold",
    "url": "https://html5games.plak365games.com/bunnicula-rescuing-harold/",
    "thumbnail": "./thumbnails/bunnicula-rescuing-harold.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 35,
    "name": "Burgermaker",
    "slug": "burgermaker",
    "url": "https://html5games.plak365games.com/burgermaker/",
    "thumbnail": "./thumbnails/burgermaker.ico",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 36,
    "name": "C B Crash Bernball",
    "slug": "c-b-crash-bernball",
    "url": "https://html5games.plak365games.com/c-b-crash-bernball/",
    "thumbnail": "./thumbnails/c-b-crash-bernball.png",
    "categories": [
      "All Games",
      "Sports",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 37,
    "name": "Candyfusion",
    "slug": "candyfusion",
    "url": "https://html5games.plak365games.com/candyfusion/",
    "thumbnail": "./thumbnails/candyfusion.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle",
      "Soothing"
    ]
  },
  {
    "id": 38,
    "name": "Candyrush",
    "slug": "candyrush",
    "url": "https://html5games.plak365games.com/candyrush/",
    "thumbnail": "./thumbnails/candyrush.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle",
      "Quick Break at Work",
      "Easy to Play",
      "Games with Leaderboard",
      "Top 10 Games"
    ]
  },
  {
    "id": 39,
    "name": "Candysuperlines",
    "slug": "candysuperlines",
    "url": "https://html5games.plak365games.com/candysuperlines/",
    "thumbnail": "./thumbnails/candysuperlines.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 40,
    "name": "Car Race",
    "slug": "car-race",
    "url": "https://html5games.plak365games.com/car-race/",
    "thumbnail": "./thumbnails/car-race.png",
    "categories": [
      "All Games",
      "Arcade",
      "Games with Leaderboard",
      "Top 10 Games"
    ]
  },
  {
    "id": 41,
    "name": "Cars",
    "slug": "cars",
    "url": "https://html5games.plak365games.com/cars/",
    "thumbnail": "./thumbnails/cars.png",
    "categories": [
      "All Games",
      "Arcade"
    ]
  },
  {
    "id": 42,
    "name": "Cat Action",
    "slug": "cat-action",
    "url": "https://html5games.plak365games.com/cat-action/",
    "thumbnail": "./thumbnails/cat-action.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 43,
    "name": "Cat Candy",
    "slug": "cat-candy",
    "url": "https://html5games.plak365games.com/cat-candy/",
    "thumbnail": "./thumbnails/cat-candy.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 44,
    "name": "Cat Flap",
    "slug": "cat-flap",
    "url": "https://html5games.plak365games.com/cat-flap/",
    "thumbnail": "./thumbnails/cat-flap.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 45,
    "name": "Catchthemonster",
    "slug": "catchthemonster",
    "url": "https://html5games.plak365games.com/catchthemonster/",
    "thumbnail": "./thumbnails/catchthemonster.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 46,
    "name": "Chimney Port",
    "slug": "chimney-port",
    "url": "https://html5games.plak365games.com/chimney-port/",
    "thumbnail": "./thumbnails/chimney-port.png",
    "categories": [
      "All Games",
      "Soothing"
    ]
  },
  {
    "id": 47,
    "name": "Chippolino",
    "slug": "chippolino",
    "url": "https://html5games.plak365games.com/chippolino/",
    "thumbnail": "./thumbnails/chippolino.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 48,
    "name": "Circletraffic",
    "slug": "circletraffic",
    "url": "https://html5games.plak365games.com/circletraffic/",
    "thumbnail": "./thumbnails/circletraffic.png",
    "categories": [
      "All Games",
      "Arcade",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 49,
    "name": "Clansamurai",
    "slug": "clansamurai",
    "url": "https://html5games.plak365games.com/clansamurai/",
    "thumbnail": "./thumbnails/clansamurai.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 50,
    "name": "Coil Chaining",
    "slug": "coil-chaining",
    "url": "https://html5games.plak365games.com/coil-chaining/",
    "thumbnail": "./thumbnails/coil-chaining.ico",
    "categories": [
      "All Games",
      "Arcade"
    ]
  },
  {
    "id": 51,
    "name": "Colorvalley",
    "slug": "colorvalley",
    "url": "https://html5games.plak365games.com/colorvalley/",
    "thumbnail": "./thumbnails/colorvalley.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 52,
    "name": "Copter",
    "slug": "copter",
    "url": "https://html5games.plak365games.com/copter/",
    "thumbnail": "./thumbnails/copter.png",
    "categories": [
      "All Games",
      "Arcade",
      "Top 10 Games"
    ]
  },
  {
    "id": 53,
    "name": "Crazycar",
    "slug": "crazycar",
    "url": "https://html5games.plak365games.com/crazycar/",
    "thumbnail": "./thumbnails/crazycar.png",
    "categories": [
      "All Games",
      "Arcade"
    ]
  },
  {
    "id": 54,
    "name": "Crazyrunner",
    "slug": "crazyrunner",
    "url": "https://html5games.plak365games.com/crazyrunner/",
    "thumbnail": "./thumbnails/crazyrunner.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play",
      "Arcade",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 55,
    "name": "Dark Country",
    "slug": "dark-country",
    "url": "https://html5games.plak365games.com/dark-country/",
    "thumbnail": "./thumbnails/dark-country.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 56,
    "name": "Dennis Gnasher Unleashed Clone Ranger",
    "slug": "dennis-gnasher-unleashed-clone-ranger",
    "url": "https://html5games.plak365games.com/dennis-gnasher-unleashed-clone-ranger/",
    "thumbnail": "./thumbnails/dennis-gnasher-unleashed-clone-ranger.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 57,
    "name": "Descendants 2 Mal Vs Uma",
    "slug": "descendants-2-mal-vs-uma",
    "url": "https://html5games.plak365games.com/descendants-2-mal-vs-uma/",
    "thumbnail": "./thumbnails/descendants-2-mal-vs-uma.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 58,
    "name": "Dinobubbles",
    "slug": "dinobubbles",
    "url": "https://html5games.plak365games.com/dinobubbles/",
    "thumbnail": "./thumbnails/dinobubbles.png",
    "categories": [
      "All Games",
      "Soothing"
    ]
  },
  {
    "id": 59,
    "name": "Disneynow Cart Blaster",
    "slug": "disneynow-cart-blaster",
    "url": "https://html5games.plak365games.com/disneynow-cart-blaster/",
    "thumbnail": "./thumbnails/disneynow-cart-blaster.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Arcade"
    ]
  },
  {
    "id": 60,
    "name": "Dontmiss",
    "slug": "dontmiss",
    "url": "https://html5games.plak365games.com/dontmiss/",
    "thumbnail": "./thumbnails/dontmiss.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 61,
    "name": "Dora And Friends Legend Of The Lost Horses",
    "slug": "dora-and-friends-legend-of-the-lost-horses",
    "url": "https://html5games.plak365games.com/dora-and-friends-legend-of-the-lost-horses/",
    "thumbnail": "./thumbnails/dora-and-friends-legend-of-the-lost-horses.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 62,
    "name": "Dora",
    "slug": "dora",
    "url": "https://html5games.plak365games.com/dora/",
    "thumbnail": "./thumbnails/dora.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 63,
    "name": "Duckshooter",
    "slug": "duckshooter",
    "url": "https://html5games.plak365games.com/duckshooter/",
    "thumbnail": "./thumbnails/duckshooter.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 64,
    "name": "Duetto",
    "slug": "duetto",
    "url": "https://html5games.plak365games.com/duetto/",
    "thumbnail": "./thumbnails/duetto.png",
    "categories": [
      "All Games",
      "Multiplayer"
    ]
  },
  {
    "id": 65,
    "name": "Egggo",
    "slug": "egggo",
    "url": "https://html5games.plak365games.com/egggo/",
    "thumbnail": "./thumbnails/egggo.ico",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 66,
    "name": "Elena Of Avalor Adventures In Avalor",
    "slug": "elena-of-avalor-adventures-in-avalor",
    "url": "https://html5games.plak365games.com/elena-of-avalor-adventures-in-avalor/",
    "thumbnail": "./thumbnails/elena-of-avalor-adventures-in-avalor.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 67,
    "name": "Experiment",
    "slug": "experiment",
    "url": "https://html5games.plak365games.com/experiment/",
    "thumbnail": "./thumbnails/experiment.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 68,
    "name": "Firetruck",
    "slug": "firetruck",
    "url": "https://html5games.plak365games.com/firetruck/",
    "thumbnail": "./thumbnails/firetruck.png",
    "categories": [
      "All Games",
      "Arcade"
    ]
  },
  {
    "id": 69,
    "name": "Fishingfrenzy",
    "slug": "fishingfrenzy",
    "url": "https://html5games.plak365games.com/fishingfrenzy/",
    "thumbnail": "./thumbnails/fishingfrenzy.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 70,
    "name": "Flipthegun",
    "slug": "flipthegun",
    "url": "https://html5games.plak365games.com/flipthegun/",
    "thumbnail": "./thumbnails/flipthegun.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 71,
    "name": "Flyingbird",
    "slug": "flyingbird",
    "url": "https://html5games.plak365games.com/flyingbird/",
    "thumbnail": "./thumbnails/flyingbird.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 72,
    "name": "Foodfight",
    "slug": "foodfight",
    "url": "https://html5games.plak365games.com/foodfight/",
    "thumbnail": "./thumbnails/foodfight.png",
    "categories": [
      "All Games",
      "Multiplayer"
    ]
  },
  {
    "id": 73,
    "name": "Forestgame",
    "slug": "forestgame",
    "url": "https://html5games.plak365games.com/forestgame/",
    "thumbnail": "./thumbnails/forestgame.png",
    "categories": [
      "All Games",
      "Soothing"
    ]
  },
  {
    "id": 74,
    "name": "Freakymath",
    "slug": "freakymath",
    "url": "https://html5games.plak365games.com/freakymath/",
    "thumbnail": "./thumbnails/freakymath.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 75,
    "name": "Frozen Rush",
    "slug": "frozen-rush",
    "url": "https://html5games.plak365games.com/frozen-rush/",
    "thumbnail": "./thumbnails/frozen-rush.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Soothing",
      "Quick Break at Work",
      "Easy to Play",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 76,
    "name": "Ghost Country",
    "slug": "ghost-country",
    "url": "https://html5games.plak365games.com/ghost-country/",
    "thumbnail": "./thumbnails/ghost-country.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 77,
    "name": "Ghost Dropper",
    "slug": "ghost-dropper",
    "url": "https://html5games.plak365games.com/ghost-dropper/",
    "thumbnail": "./thumbnails/ghost-dropper.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 78,
    "name": "Goldie Bear Fairy Tale Forest Adventures",
    "slug": "goldie-bear-fairy-tale-forest-adventures",
    "url": "https://html5games.plak365games.com/goldie-bear-fairy-tale-forest-adventures/",
    "thumbnail": "./thumbnails/goldie-bear-fairy-tale-forest-adventures.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Soothing"
    ]
  },
  {
    "id": 79,
    "name": "Goofrunner",
    "slug": "goofrunner",
    "url": "https://html5games.plak365games.com/goofrunner/",
    "thumbnail": "./thumbnails/goofrunner.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play",
      "Arcade",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 80,
    "name": "Greatairbattles",
    "slug": "greatairbattles",
    "url": "https://html5games.plak365games.com/greatairbattles/",
    "thumbnail": "./thumbnails/greatairbattles.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 81,
    "name": "Guardians Defenders Of Mathematica",
    "slug": "guardians-defenders-of-mathematica",
    "url": "https://html5games.plak365games.com/guardians-defenders-of-mathematica/",
    "thumbnail": "./thumbnails/guardians-defenders-of-mathematica.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Train Your Brain",
      "Puzzle",
      "Action"
    ]
  },
  {
    "id": 82,
    "name": "Hanuman",
    "slug": "hanuman",
    "url": "https://html5games.plak365games.com/hanuman/",
    "thumbnail": "./thumbnails/hanuman.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Action"
    ]
  },
  {
    "id": 83,
    "name": "Henry Danger Whats Your Danger Ous Power",
    "slug": "henry-danger-whats-your-danger-ous-power",
    "url": "https://html5games.plak365games.com/henry-danger-whats-your-danger-ous-power/",
    "thumbnail": "./thumbnails/henry-danger-whats-your-danger-ous-power.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 84,
    "name": "Henry Danger Whos Your Enemy",
    "slug": "henry-danger-whos-your-enemy",
    "url": "https://html5games.plak365games.com/henry-danger-whos-your-enemy/",
    "thumbnail": "./thumbnails/henry-danger-whos-your-enemy.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 85,
    "name": "Heroinsuperactionadventure",
    "slug": "heroinsuperactionadventure",
    "url": "https://html5games.plak365games.com/heroinsuperactionadventure/",
    "thumbnail": "./thumbnails/heroinsuperactionadventure.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 86,
    "name": "Hiddenmistry",
    "slug": "hiddenmistry",
    "url": "https://html5games.plak365games.com/hiddenmistry/",
    "thumbnail": "./thumbnails/hiddenmistry.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 87,
    "name": "Hurdles",
    "slug": "hurdles",
    "url": "https://html5games.plak365games.com/hurdles/",
    "thumbnail": "./thumbnails/hurdles.ico",
    "categories": [
      "All Games",
      "Sports"
    ]
  },
  {
    "id": 88,
    "name": "Indiaraandtheskullgold",
    "slug": "indiaraandtheskullgold",
    "url": "https://html5games.plak365games.com/indiaraandtheskullgold/",
    "thumbnail": "./thumbnails/indiaraandtheskullgold.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 89,
    "name": "Isleofthe",
    "slug": "isleofthe",
    "url": "https://html5games.plak365games.com/isleofthe/",
    "thumbnail": "./thumbnails/isleofthe.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 90,
    "name": "Jackadventures",
    "slug": "jackadventures",
    "url": "https://html5games.plak365games.com/jackadventures/",
    "thumbnail": "./thumbnails/jackadventures.png",
    "categories": [
      "All Games",
      "Arcade"
    ]
  },
  {
    "id": 91,
    "name": "Kill Rabbit",
    "slug": "kill-rabbit",
    "url": "https://html5games.plak365games.com/kill-rabbit/",
    "thumbnail": "./thumbnails/kill-rabbit.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 92,
    "name": "Kim Possible Mission Improbable",
    "slug": "kim-possible-mission-improbable",
    "url": "https://html5games.plak365games.com/kim-possible-mission-improbable/",
    "thumbnail": "./thumbnails/kim-possible-mission-improbable.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 93,
    "name": "Kung Fu Panda Pawsome Panda",
    "slug": "kung-fu-panda-pawsome-panda",
    "url": "https://html5games.plak365games.com/kung-fu-panda-pawsome-panda/",
    "thumbnail": "./thumbnails/kung-fu-panda-pawsome-panda.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 94,
    "name": "Lego Star Wars Battle Run",
    "slug": "lego-star-wars-battle-run",
    "url": "https://html5games.plak365games.com/lego-star-wars-battle-run/",
    "thumbnail": "./thumbnails/lego-star-wars-battle-run.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Quick Break at Work",
      "Easy to Play",
      "Action",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 95,
    "name": "Looney Tunes Acme Rocket Dash",
    "slug": "looney-tunes-acme-rocket-dash",
    "url": "https://html5games.plak365games.com/looney-tunes-acme-rocket-dash/",
    "thumbnail": "./thumbnails/looney-tunes-acme-rocket-dash.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 96,
    "name": "Looney Tunes Recess",
    "slug": "looney-tunes-recess",
    "url": "https://html5games.plak365games.com/looney-tunes-recess/",
    "thumbnail": "./thumbnails/looney-tunes-recess.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 97,
    "name": "Looney Tunes Snap",
    "slug": "looney-tunes-snap",
    "url": "https://html5games.plak365games.com/looney-tunes-snap/",
    "thumbnail": "./thumbnails/looney-tunes-snap.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 98,
    "name": "Looney Tunes Tweety Takes Off",
    "slug": "looney-tunes-tweety-takes-off",
    "url": "https://html5games.plak365games.com/looney-tunes-tweety-takes-off/",
    "thumbnail": "./thumbnails/looney-tunes-tweety-takes-off.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 99,
    "name": "Malvsuma",
    "slug": "malvsuma",
    "url": "https://html5games.plak365games.com/malvsuma/",
    "thumbnail": "./thumbnails/malvsuma.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 100,
    "name": "Match Color",
    "slug": "match-color",
    "url": "https://html5games.plak365games.com/match-color/",
    "thumbnail": "./thumbnails/match-color.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 101,
    "name": "Mickyminnie",
    "slug": "mickyminnie",
    "url": "https://html5games.plak365games.com/mickyminnie/",
    "thumbnail": "./thumbnails/mickyminnie.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 102,
    "name": "Mind Grands",
    "slug": "mind-grands",
    "url": "https://html5games.plak365games.com/mind-grands/",
    "thumbnail": "./thumbnails/mind-grands.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 103,
    "name": "Minigolfworld",
    "slug": "minigolfworld",
    "url": "https://html5games.plak365games.com/minigolfworld/",
    "thumbnail": "./thumbnails/minigolfworld.png",
    "categories": [
      "All Games",
      "Sports"
    ]
  },
  {
    "id": 104,
    "name": "Mr Bean Backyard Junk",
    "slug": "mr-bean-backyard-junk",
    "url": "https://html5games.plak365games.com/mr-bean-backyard-junk/",
    "thumbnail": "./thumbnails/mr-bean-backyard-junk.ico",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 105,
    "name": "Mr Bean Bean Skidding",
    "slug": "mr-bean-bean-skidding",
    "url": "https://html5games.plak365games.com/mr-bean-bean-skidding/",
    "thumbnail": "./thumbnails/mr-bean-bean-skidding.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 106,
    "name": "Mr Bean Goldfish Loopy Loopy",
    "slug": "mr-bean-goldfish-loopy-loopy",
    "url": "https://html5games.plak365games.com/mr-bean-goldfish-loopy-loopy/",
    "thumbnail": "./thumbnails/mr-bean-goldfish-loopy-loopy.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 107,
    "name": "Mr Bean Matching Pairs",
    "slug": "mr-bean-matching-pairs",
    "url": "https://html5games.plak365games.com/mr-bean-matching-pairs/",
    "thumbnail": "./thumbnails/mr-bean-matching-pairs.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 108,
    "name": "Ninja Jumper",
    "slug": "ninja-jumper",
    "url": "https://html5games.plak365games.com/ninja-jumper/",
    "thumbnail": "./thumbnails/ninja-jumper.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play",
      "Action",
      "Top 10 Games"
    ]
  },
  {
    "id": 109,
    "name": "Ninjarun",
    "slug": "ninjarun",
    "url": "https://html5games.plak365games.com/ninjarun/",
    "thumbnail": "./thumbnails/ninjarun.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play",
      "Action",
      "Arcade",
      "Games with Leaderboard",
      "Top 10 Games"
    ]
  },
  {
    "id": 110,
    "name": "Pancakepileup",
    "slug": "pancakepileup",
    "url": "https://html5games.plak365games.com/pancakepileup/",
    "thumbnail": "./thumbnails/pancakepileup.ico",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 111,
    "name": "Pin The Ball",
    "slug": "pin-the-ball",
    "url": "https://html5games.plak365games.com/pin-the-ball/",
    "thumbnail": "./thumbnails/pin-the-ball.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 112,
    "name": "Plane",
    "slug": "plane",
    "url": "https://html5games.plak365games.com/plane/",
    "thumbnail": "./thumbnails/plane.png",
    "categories": [
      "All Games",
      "Arcade",
      "Top 10 Games"
    ]
  },
  {
    "id": 113,
    "name": "Platformer",
    "slug": "platformer",
    "url": "https://html5games.plak365games.com/platformer/",
    "thumbnail": "./thumbnails/platformer.png",
    "categories": [
      "All Games",
      "Arcade"
    ]
  },
  {
    "id": 114,
    "name": "Pond",
    "slug": "pond",
    "url": "https://html5games.plak365games.com/pond/",
    "thumbnail": "./thumbnails/pond.ico",
    "categories": [
      "All Games",
      "Soothing"
    ]
  },
  {
    "id": 115,
    "name": "Popsbilliards",
    "slug": "popsbilliards",
    "url": "https://html5games.plak365games.com/popsbilliards/",
    "thumbnail": "./thumbnails/popsbilliards.png",
    "categories": [
      "All Games",
      "Sports"
    ]
  },
  {
    "id": 116,
    "name": "Princessgoldblade",
    "slug": "princessgoldblade",
    "url": "https://html5games.plak365games.com/princessgoldblade/",
    "thumbnail": "./thumbnails/princessgoldblade.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 117,
    "name": "Racer",
    "slug": "racer",
    "url": "https://html5games.plak365games.com/racer/",
    "thumbnail": "./thumbnails/racer.png",
    "categories": [
      "All Games",
      "Arcade",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 118,
    "name": "Rafting",
    "slug": "rafting",
    "url": "https://html5games.plak365games.com/rafting/",
    "thumbnail": "./thumbnails/rafting.png",
    "categories": [
      "All Games",
      "Arcade"
    ]
  },
  {
    "id": 119,
    "name": "Railrush",
    "slug": "railrush",
    "url": "https://html5games.plak365games.com/railrush/",
    "thumbnail": "./thumbnails/railrush.ico",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 120,
    "name": "Reasoning",
    "slug": "reasoning",
    "url": "https://html5games.plak365games.com/reasoning/",
    "thumbnail": "./thumbnails/reasoning.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 121,
    "name": "Robberrun",
    "slug": "robberrun",
    "url": "https://html5games.plak365games.com/robberrun/",
    "thumbnail": "./thumbnails/robberrun.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play",
      "Arcade",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 122,
    "name": "Save Life",
    "slug": "save-life",
    "url": "https://html5games.plak365games.com/save-life/",
    "thumbnail": "./thumbnails/save-life.jpg",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 123,
    "name": "Scooby Doo And Guess Who Ghost Creator",
    "slug": "scooby-doo-and-guess-who-ghost-creator",
    "url": "https://html5games.plak365games.com/scooby-doo-and-guess-who-ghost-creator/",
    "thumbnail": "./thumbnails/scooby-doo-and-guess-who-ghost-creator.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Action"
    ]
  },
  {
    "id": 124,
    "name": "Scooby Doo And Guess Who Midnight Munchies",
    "slug": "scooby-doo-and-guess-who-midnight-munchies",
    "url": "https://html5games.plak365games.com/scooby-doo-and-guess-who-midnight-munchies/",
    "thumbnail": "./thumbnails/scooby-doo-and-guess-who-midnight-munchies.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 125,
    "name": "Scooby Doo Snap",
    "slug": "scooby-doo-snap",
    "url": "https://html5games.plak365games.com/scooby-doo-snap/",
    "thumbnail": "./thumbnails/scooby-doo-snap.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 126,
    "name": "Side Chain",
    "slug": "side-chain",
    "url": "https://html5games.plak365games.com/side-chain/",
    "thumbnail": "./thumbnails/side-chain.png",
    "categories": [
      "All Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 127,
    "name": "Sky War",
    "slug": "sky-war",
    "url": "https://html5games.plak365games.com/sky-war/",
    "thumbnail": "./thumbnails/sky-war.gif",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 128,
    "name": "Spider Man Mysterio Rush Game",
    "slug": "spider-man-mysterio-rush-game",
    "url": "https://html5games.plak365games.com/spider-man-mysterio-rush-game/",
    "thumbnail": "./thumbnails/spider-man-mysterio-rush-game.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Quick Break at Work",
      "Easy to Play",
      "Action",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 129,
    "name": "Spongebob Squarepants Bikini Bottom Mysteries Search",
    "slug": "spongebob-squarepants-bikini-bottom-mysteries-search",
    "url": "https://html5games.plak365games.com/spongebob-squarepants-bikini-bottom-mysteries-search/",
    "thumbnail": "./thumbnails/spongebob-squarepants-bikini-bottom-mysteries-search.webp",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 130,
    "name": "Spongebob Squarepants Lost Treasures",
    "slug": "spongebob-squarepants-lost-treasures",
    "url": "https://html5games.plak365games.com/spongebob-squarepants-lost-treasures/",
    "thumbnail": "./thumbnails/spongebob-squarepants-lost-treasures.webp",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 131,
    "name": "Spongebob Squarepants Marble Bash",
    "slug": "spongebob-squarepants-marble-bash",
    "url": "https://html5games.plak365games.com/spongebob-squarepants-marble-bash/",
    "thumbnail": "./thumbnails/spongebob-squarepants-marble-bash.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 132,
    "name": "Spongebob Squarepants Which Krabby Patty Are You",
    "slug": "spongebob-squarepants-which-krabby-patty-are-you",
    "url": "https://html5games.plak365games.com/spongebob-squarepants-which-krabby-patty-are-you/",
    "thumbnail": "./thumbnails/spongebob-squarepants-which-krabby-patty-are-you.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 133,
    "name": "Star Rocket",
    "slug": "star-rocket",
    "url": "https://html5games.plak365games.com/star-rocket/",
    "thumbnail": "./thumbnails/star-rocket.png",
    "categories": [
      "All Games",
      "Arcade"
    ]
  },
  {
    "id": 134,
    "name": "Star Wars Arcade",
    "slug": "star-wars-arcade",
    "url": "https://html5games.plak365games.com/star-wars-arcade/",
    "thumbnail": "./thumbnails/star-wars-arcade.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Action",
      "Arcade"
    ]
  },
  {
    "id": 135,
    "name": "Star Wars Rebels Chopper Chase",
    "slug": "star-wars-rebels-chopper-chase",
    "url": "https://html5games.plak365games.com/star-wars-rebels-chopper-chase/",
    "thumbnail": "./thumbnails/star-wars-rebels-chopper-chase.jpg",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Action"
    ]
  },
  {
    "id": 136,
    "name": "Star Wars Rebels Special Ops",
    "slug": "star-wars-rebels-special-ops",
    "url": "https://html5games.plak365games.com/star-wars-rebels-special-ops/",
    "thumbnail": "./thumbnails/star-wars-rebels-special-ops.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Action"
    ]
  },
  {
    "id": 137,
    "name": "Star Wars Rebels Team Tactics",
    "slug": "star-wars-rebels-team-tactics",
    "url": "https://html5games.plak365games.com/star-wars-rebels-team-tactics/",
    "thumbnail": "./thumbnails/star-wars-rebels-team-tactics.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Multiplayer",
      "Action"
    ]
  },
  {
    "id": 138,
    "name": "Star Wars Rogue One Boots On The Ground",
    "slug": "star-wars-rogue-one-boots-on-the-ground",
    "url": "https://html5games.plak365games.com/star-wars-rogue-one-boots-on-the-ground/",
    "thumbnail": "./thumbnails/star-wars-rogue-one-boots-on-the-ground.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Action"
    ]
  },
  {
    "id": 139,
    "name": "Stormshadowrunner",
    "slug": "stormshadowrunner",
    "url": "https://html5games.plak365games.com/stormshadowrunner/",
    "thumbnail": "./thumbnails/stormshadowrunner.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play",
      "Action",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 140,
    "name": "Swing",
    "slug": "swing",
    "url": "https://html5games.plak365games.com/swing/",
    "thumbnail": "./thumbnails/swing.png",
    "categories": [
      "All Games",
      "Sports"
    ]
  },
  {
    "id": 141,
    "name": "Table Tennis Ultra Mega Tournament",
    "slug": "table-tennis-ultra-mega-tournament",
    "url": "https://html5games.plak365games.com/table-tennis-ultra-mega-tournament/",
    "thumbnail": "./thumbnails/table-tennis-ultra-mega-tournament.png",
    "categories": [
      "All Games",
      "Sports"
    ]
  },
  {
    "id": 142,
    "name": "Tankdefender",
    "slug": "tankdefender",
    "url": "https://html5games.plak365games.com/tankdefender/",
    "thumbnail": "./thumbnails/tankdefender.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 143,
    "name": "Teenage Mutant Ninja Turtles Bumper Bros",
    "slug": "teenage-mutant-ninja-turtles-bumper-bros",
    "url": "https://html5games.plak365games.com/teenage-mutant-ninja-turtles-bumper-bros/",
    "thumbnail": "./thumbnails/teenage-mutant-ninja-turtles-bumper-bros.webp",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Multiplayer",
      "Action"
    ]
  },
  {
    "id": 144,
    "name": "Teenage Mutant Ninja Turtles City Showdown",
    "slug": "teenage-mutant-ninja-turtles-city-showdown",
    "url": "https://html5games.plak365games.com/teenage-mutant-ninja-turtles-city-showdown/",
    "thumbnail": "./thumbnails/teenage-mutant-ninja-turtles-city-showdown.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Action"
    ]
  },
  {
    "id": 145,
    "name": "Teenage Mutant Ninja Turtles Epic Mutant Missions",
    "slug": "teenage-mutant-ninja-turtles-epic-mutant-missions",
    "url": "https://html5games.plak365games.com/teenage-mutant-ninja-turtles-epic-mutant-missions/",
    "thumbnail": "./thumbnails/teenage-mutant-ninja-turtles-epic-mutant-missions.webp",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Action"
    ]
  },
  {
    "id": 146,
    "name": "Terror Attack",
    "slug": "terror-attack",
    "url": "https://html5games.plak365games.com/terror-attack/",
    "thumbnail": "./thumbnails/terror-attack.png",
    "categories": [
      "All Games",
      "Action"
    ]
  },
  {
    "id": 147,
    "name": "The Adventures Of Puss In Boots Barrel Run",
    "slug": "the-adventures-of-puss-in-boots-barrel-run",
    "url": "https://html5games.plak365games.com/the-adventures-of-puss-in-boots-barrel-run/",
    "thumbnail": "./thumbnails/the-adventures-of-puss-in-boots-barrel-run.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Quick Break at Work",
      "Easy to Play",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 148,
    "name": "The Adventures Of Puss In Boots Catch The Thief",
    "slug": "the-adventures-of-puss-in-boots-catch-the-thief",
    "url": "https://html5games.plak365games.com/the-adventures-of-puss-in-boots-catch-the-thief/",
    "thumbnail": "./thumbnails/the-adventures-of-puss-in-boots-catch-the-thief.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 149,
    "name": "The Incredible Hulk Chitauri Takedown",
    "slug": "the-incredible-hulk-chitauri-takedown",
    "url": "https://html5games.plak365games.com/the-incredible-hulk-chitauri-takedown/",
    "thumbnail": "./thumbnails/the-incredible-hulk-chitauri-takedown.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Action"
    ]
  },
  {
    "id": 150,
    "name": "The Powerpuff Girls Hypno Bliss",
    "slug": "the-powerpuff-girls-hypno-bliss",
    "url": "https://html5games.plak365games.com/the-powerpuff-girls-hypno-bliss/",
    "thumbnail": "./thumbnails/the-powerpuff-girls-hypno-bliss.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 151,
    "name": "The Powerpuff Girls Mech Mayhem",
    "slug": "the-powerpuff-girls-mech-mayhem",
    "url": "https://html5games.plak365games.com/the-powerpuff-girls-mech-mayhem/",
    "thumbnail": "./thumbnails/the-powerpuff-girls-mech-mayhem.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 152,
    "name": "The Powerpuff Girls Morning Mix Up",
    "slug": "the-powerpuff-girls-morning-mix-up",
    "url": "https://html5games.plak365games.com/the-powerpuff-girls-morning-mix-up/",
    "thumbnail": "./thumbnails/the-powerpuff-girls-morning-mix-up.ico",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 153,
    "name": "Thundercats Roar Character Creator",
    "slug": "thundercats-roar-character-creator",
    "url": "https://html5games.plak365games.com/thundercats-roar-character-creator/",
    "thumbnail": "./thumbnails/thundercats-roar-character-creator.ico",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 154,
    "name": "Timeball",
    "slug": "timeball",
    "url": "https://html5games.plak365games.com/timeball/",
    "thumbnail": "./thumbnails/timeball.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 155,
    "name": "Tom And Jerry Backyard Hoops",
    "slug": "tom-and-jerry-backyard-hoops",
    "url": "https://html5games.plak365games.com/tom-and-jerry-backyard-hoops/",
    "thumbnail": "./thumbnails/tom-and-jerry-backyard-hoops.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Sports"
    ]
  },
  {
    "id": 156,
    "name": "Tom And Jerry Blast Off",
    "slug": "tom-and-jerry-blast-off",
    "url": "https://html5games.plak365games.com/tom-and-jerry-blast-off/",
    "thumbnail": "./thumbnails/tom-and-jerry-blast-off.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 157,
    "name": "Tom And Jerry Broom Riders",
    "slug": "tom-and-jerry-broom-riders",
    "url": "https://html5games.plak365games.com/tom-and-jerry-broom-riders/",
    "thumbnail": "./thumbnails/tom-and-jerry-broom-riders.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 158,
    "name": "Tom And Jerry Cats Gone Bats",
    "slug": "tom-and-jerry-cats-gone-bats",
    "url": "https://html5games.plak365games.com/tom-and-jerry-cats-gone-bats/",
    "thumbnail": "./thumbnails/tom-and-jerry-cats-gone-bats.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 159,
    "name": "Tom And Jerry Chasing Jerry",
    "slug": "tom-and-jerry-chasing-jerry",
    "url": "https://html5games.plak365games.com/tom-and-jerry-chasing-jerry/",
    "thumbnail": "./thumbnails/tom-and-jerry-chasing-jerry.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 160,
    "name": "Tom And Jerry Dont Make A Mess",
    "slug": "tom-and-jerry-dont-make-a-mess",
    "url": "https://html5games.plak365games.com/tom-and-jerry-dont-make-a-mess/",
    "thumbnail": "./thumbnails/tom-and-jerry-dont-make-a-mess.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 161,
    "name": "Tom And Jerry Dress Up",
    "slug": "tom-and-jerry-dress-up",
    "url": "https://html5games.plak365games.com/tom-and-jerry-dress-up/",
    "thumbnail": "./thumbnails/tom-and-jerry-dress-up.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 162,
    "name": "Tom And Jerry Freefalling Tom",
    "slug": "tom-and-jerry-freefalling-tom",
    "url": "https://html5games.plak365games.com/tom-and-jerry-freefalling-tom/",
    "thumbnail": "./thumbnails/tom-and-jerry-freefalling-tom.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 163,
    "name": "Tom And Jerry Matching Pairs",
    "slug": "tom-and-jerry-matching-pairs",
    "url": "https://html5games.plak365games.com/tom-and-jerry-matching-pairs/",
    "thumbnail": "./thumbnails/tom-and-jerry-matching-pairs.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games",
      "Train Your Brain",
      "Puzzle"
    ]
  },
  {
    "id": 164,
    "name": "Tom And Jerry River Recycle",
    "slug": "tom-and-jerry-river-recycle",
    "url": "https://html5games.plak365games.com/tom-and-jerry-river-recycle/",
    "thumbnail": "./thumbnails/tom-and-jerry-river-recycle.png",
    "categories": [
      "All Games",
      "VIP Games",
      "Top 10 Games"
    ]
  },
  {
    "id": 165,
    "name": "Tom Jump",
    "slug": "tom-jump",
    "url": "https://html5games.plak365games.com/tom-jump/",
    "thumbnail": "./thumbnails/tom-jump.png",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 166,
    "name": "Trafficracer",
    "slug": "trafficracer",
    "url": "https://html5games.plak365games.com/trafficracer/",
    "thumbnail": "./thumbnails/trafficracer.png",
    "categories": [
      "All Games",
      "Arcade",
      "Games with Leaderboard",
      "Top 10 Games"
    ]
  },
  {
    "id": 167,
    "name": "Trickshotball",
    "slug": "trickshotball",
    "url": "https://html5games.plak365games.com/trickshotball/",
    "thumbnail": "./thumbnails/trickshotball.ico",
    "categories": [
      "All Games",
      "Sports",
      "Quick Break at Work",
      "Easy to Play"
    ]
  },
  {
    "id": 168,
    "name": "Violencerun",
    "slug": "violencerun",
    "url": "https://html5games.plak365games.com/violencerun/",
    "thumbnail": "./thumbnails/violencerun.ico",
    "categories": [
      "All Games",
      "Quick Break at Work",
      "Easy to Play",
      "Action",
      "Games with Leaderboard"
    ]
  },
  {
    "id": 169,
    "name": "X Wing Fighter",
    "slug": "x-wing-fighter",
    "url": "https://html5games.plak365games.com/x-wing-fighter/",
    "thumbnail": "./thumbnails/x-wing-fighter.jpg",
    "categories": [
      "All Games",
      "Arcade"
    ]
  },
  {
    "id": 170,
    "name": "Zombieworld",
    "slug": "zombieworld",
    "url": "https://html5games.plak365games.com/zombieworld/",
    "thumbnail": "./thumbnails/zombieworld.png",
    "categories": [
      "All Games",
      "Action",
      "Top 10 Games"
    ]
  }
];

export function getGamesByEndpoint(endpointKey) {
  if (endpointKey === 'all-games') return GAMES_DATA;
  const label = CATEGORY_KEYS[endpointKey];
  if (!label) return [];
  return GAMES_DATA.filter((g) => g.categories.includes(label));
}

export function getNewReleases(limit = 12) {
  return GAMES_DATA.slice(0, limit);
}

export function getGamesByFilter(category) {
  if (category === 'all') return GAMES_DATA;
  return GAMES_DATA.filter((g) => g.categories.includes(category));
}
